// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSMirU0DgOG2fw5D3zAI-Eg-zGvVtYh0g',
    appId: '1:748867291558:web:2274b04dd5ee68423fa767',
    messagingSenderId: '748867291558',
    projectId: 'fitbot-8aaa1',
    authDomain: 'fitbot-8aaa1.firebaseapp.com',
    storageBucket: 'fitbot-8aaa1.firebasestorage.app',
    measurementId: 'G-7YKKEK0RG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4gI2HwDiKVv4i90Xj2VOFx1CbBficdq8',
    appId: '1:748867291558:android:c9bc1736c93e92bd3fa767',
    messagingSenderId: '748867291558',
    projectId: 'fitbot-8aaa1',
    storageBucket: 'fitbot-8aaa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZrPuTqmGxyz3hkOy-WMdh8zt_WG5X6t0',
    appId: '1:748867291558:ios:544e3347461944943fa767',
    messagingSenderId: '748867291558',
    projectId: 'fitbot-8aaa1',
    storageBucket: 'fitbot-8aaa1.firebasestorage.app',
    iosBundleId: 'com.example.fitbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZrPuTqmGxyz3hkOy-WMdh8zt_WG5X6t0',
    appId: '1:748867291558:ios:544e3347461944943fa767',
    messagingSenderId: '748867291558',
    projectId: 'fitbot-8aaa1',
    storageBucket: 'fitbot-8aaa1.firebasestorage.app',
    iosBundleId: 'com.example.fitbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSMirU0DgOG2fw5D3zAI-Eg-zGvVtYh0g',
    appId: '1:748867291558:web:16dffcac01cf43713fa767',
    messagingSenderId: '748867291558',
    projectId: 'fitbot-8aaa1',
    authDomain: 'fitbot-8aaa1.firebaseapp.com',
    storageBucket: 'fitbot-8aaa1.firebasestorage.app',
    measurementId: 'G-9EPBWX637H',
  );
}
